### ISSUE TITLE
Sample Code doesn't compile...

### ISSUE THREAD

**Issue by belmonmi** [kentcb/YouIandReactiveUI#12]
Hi Kent,

  I just paid $67.49 plus shipping to Blurb.com for your book. Got your book, started to read, follow your instructions. Got the source code - cannot compile.  A lot of interfaces and classes not found (IReactiveDerivedList,  ReactiveList, etc.). I know you wrote this book for version 8 of ReactiveUI and I expected the changes in the framework and I understand that making new edition of the book is too much to ask. But the source code? You are the expert in ReactiveUI, how hard it is for you to load the source, comment out the code what is obsolete, replace it with new classes and interfaces, put a comment why you did it.  
At the current state, for programmers like myself, who is trying to learn ReactiveUI your book is useless. First of all: why anyone would like to learn an obsolete concepts without clear path how to move forward (a working source code could do the job). Second: first impression of the ReactiveUI framework that it is changing to much and maintain source code will be a nightmare for the long run enterprise projects.
Third: You have a good looking book, well though through, well organized and may be very useful for an experience ReactiveUI programmer, but for a beginner => zero utility value.
Please do not take my comment in a wrong way. Just, I feel like a child who got a toy what he was waiting for so long, finally it came, but batteries was not included...

Thank you,
Michael.

**Comment by dtiholden** [comment]
Same problem. The main ReactiveUI site should not be linking to this book anymore.

**Comment by kentcb** [comment]
Hi there. Sorry for the slow response. COVID has made life super hectic for me and my work, with today being my first day (or night) off in 2.5 months.

I've just upgraded to latest VS and tried building the `master` branch of the repo and it built and ran. Can I please clarify whether that is not the case for you? Or are you asking for it to build against the latest RxUI bits?

**Comment by belmonmi** [comment]
Kent,
 As a standard practice, when I open new solution or project, I always update it to the latest packages, unless it was specify not to do that. This is exactly what I did with the source code for your book and after building the project 160 compiler errors was generated.  
I don't see any point of learning how to use old or obsolete libraries, because for application development I'm going to use current and maintained release, not the forgotten branch.  Your code is compiled with old packages as it should and expected, but not with the latest releases. And I understand that you have no time to update your source code every time when new ReactiveUI packages released, but the last release of ReactiveUI was in May 2018. A lot of interfaces and classes were moved around and disappeared and for ReactiveUI beginner it is very hard to make a sence from all that mess.

Sincerely,
Michael.

**Comment by kentcb** [comment]
This request presents some problems:

1. Many passages in the book that discuss sample code will become out of sync, potentially causing a lot of confusion for readers. As an extreme example, the entire chapter on `ReactiveList` would have no corresponding samples, since that feature is deprecated (replaced by DynamicData).
2. If I were to update the code, for how long would I be expected to do so? And how frequently? Doing so would be a non-trivial undertaking and impossible for me to predict how much of my time would be required, so it doesn't seem reasonable nor financially viable for me to commit to that. Nor have I ever owned a technical book that did this (beyond minor tweaks that were bug fixes in sample code rather than updating the dependencies).

Granted, I could at least partially solve 1 by pushing code updates to new branches named after the ReactiveUI version they reflect. So it's 2 that is the real sticking point for me. I just can't imagine how I would have found the time over the past several years to keep on updating the sample code as new versions of RxUI were released, even at a low cadence. In part, this is due to COVID and life events, but even without that there are dozens of projects vying for my attention. Heck, it's taken an embarrassingly long time for me to even reply to this issue, but life has been a busy mess for me for a while now.

That said, it _was_ always an assumption on my part that the sample code should remain in sync with the book, so I wanted to validate that assumption, if only to learn for next time I release a book. To that end, I did [a Twitter poll](https://twitter.com/kent_boogaart/status/1494232783782178819) and here are the results:

![image](https://user-images.githubusercontent.com/1901832/154869408-73366fa7-808e-48a3-850b-3491be8324b5.png)

So the majority do think that the code should align with the book. And most of the comments reflect my thoughts around the financial viability of doing otherwise, not to mention the time required.

As such, I hope you can accept me closing this as "won't fix", so to speak. If/when I release another book, I'll do my best to ensure that it is as clear as possible that the book and sample code will remain aligned. Perhaps it's as simple as including a ReactiveUI version number in the book's subtitle or something...
