### ISSUE TITLE
EBook

### ISSUE THREAD

**Issue by jeremy-morren** [kentcb/YouIandReactiveUI#13]
I live in an out-of-the-way place and shipping books is a huge pain.  Can I buy an eBook version anywhere?

**Comment by zsolt-kolbay** [comment]
I would also appreciate if the eBook version was available. Is there a reason it's only available in non-digital format?

**Comment by squirrelfeng** [comment]
Hello, is there no plan to publish the ebook now? I also live in the country unreachable of the address.
Even ebook is same price as hardcopy is acceptable. Thanks

**Comment by kentcb** [comment]
Thanks all for your interest, and apologies for a delayed response.

The first edition of the book will forever be print-only, and only available via Blurb (a platform with regrettable limitations and pain points, but it is what was available at the time of publication). I'm really sorry for those that have trouble getting the book because of Blurb limitations, but there's little I can do about this for the first edition.

Calling it the first edition hints at the possibility of a second, and that has long been my plan. However, life, health, and the crazy times we live in have all conspired to prevent me making any headway so far. That said, I can promise that I do want to make a start on this as soon as my circumstances allow, and it will _not_ be sold via Blurb and it _will_ have some kind of electronic option.

The best way to hear of developments is to sign up to [the subscriber list](https://kent-boogaart.com/you-i-and-reactiveui/#subscribe). I will certainly send an email out there if/when things change.
